# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'UIView.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1353, 753)
        MainWindow.setStyleSheet("background-color: rgb(2, 159, 164);")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(-350, 90, 581, 481))
        self.label.setText("")
        self.label.setPixmap(QtGui.QPixmap("asset/blob.png"))
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(1130, 260, 581, 481))
        self.label_2.setText("")
        self.label_2.setPixmap(QtGui.QPixmap("asset/blob.png"))
        self.label_2.setObjectName("label_2")
        self.startButton = QtWidgets.QPushButton(self.centralwidget)
        self.startButton.setGeometry(QtCore.QRect(560, 420, 200, 80))
        self.startButton.setMinimumSize(QtCore.QSize(200, 80))
        self.startButton.setStyleSheet("QPushButton {\n"
"    background-color: #1E7878;\n"
"    border: none;\n"
"    color: rgb(39, 158, 158) ;    \n"
"    border-top: 2px solid rgb(23, 95, 95);\n"
"    border-left: 2px solid rgb(23, 95, 95);\n"
"    border-right: 2px solid rgb(23, 95, 95);\n"
"    border-bottom: 2px solid rgb(23, 95, 95);\n"
"    border-radius: 25px;\n"
"    font-family: \"Poppins\";\n"
"    font-weight: bold;\n"
"    font-size: 32px;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: rgb(42, 167, 167);\n"
"    border: none;\n"
"    color:  rgb(26, 108, 108);\n"
"    border-top: 2px solid rgb(41, 173, 173);\n"
"    border-left: 2px solid rgb(41, 173, 173);\n"
"    border-right: 2px solid rgb(41, 173, 173);\n"
"    border-bottom: 2px solid rgb(41, 173, 173);\n"
"\n"
"    font-family: \"Poppins\";\n"
"    font-weight: bold;\n"
"    font-size: 32px;\n"
"    transition-delay: 1s\n"
"    \n"
"}")
        self.startButton.setObjectName("startButton")
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.startButton.setText(_translate("MainWindow", "START"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
