# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'UIView.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from menu import Ui_MenuWindow


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1353, 753)
        MainWindow.setStyleSheet("background-color: rgb(2, 159, 164);")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(-340, 50, 581, 481))
        self.label.setText("")
        self.label.setPixmap(QtGui.QPixmap("asset/blob.png"))
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(1130, 260, 581, 481))
        self.label_2.setText("")
        self.label_2.setPixmap(QtGui.QPixmap("asset/blob.png"))
        self.label_2.setObjectName("label_2")
        self.startButton = QtWidgets.QPushButton(self.centralwidget)
        self.startButton.setGeometry(QtCore.QRect(580, 420, 200, 80))
        self.startButton.setMinimumSize(QtCore.QSize(200, 80))
        self.startButton.setStyleSheet("QPushButton {\n"
"    background-color: #1E7878;\n"
"    border: none;\n"
"    color: rgb(39, 158, 158) ;    \n"
"    border-top: 2px solid rgb(23, 95, 95);\n"
"    border-left: 2px solid rgb(23, 95, 95);\n"
"    border-right: 2px solid rgb(23, 95, 95);\n"
"    border-bottom: 2px solid rgb(23, 95, 95);\n"
"    border-radius: 25px;\n"
"    font-family: \"Poppins\";\n"
"    font-weight: bold;\n"
"    font-size: 32px;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: rgb(42, 167, 167);\n"
"    border: none;\n"
"    color:  rgb(26, 108, 108);\n"
"    border-top: 2px solid rgb(41, 173, 173);\n"
"    border-left: 2px solid rgb(41, 173, 173);\n"
"    border-right: 2px solid rgb(41, 173, 173);\n"
"    border-bottom: 2px solid rgb(41, 173, 173);\n"
"\n"
"    font-family: \"Poppins\";\n"
"    font-weight: bold;\n"
"    font-size: 32px;\n"
"    transition-delay: 1s\n"
"    \n"
"}")
        self.startButton.setObjectName("startButton")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(220, 140, 911, 231))
        self.label_3.setText("")
        self.label_3.setPixmap(QtGui.QPixmap("asset/title.png"))
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setGeometry(QtCore.QRect(210, 420, 271, 271))
        self.label_4.setText("")
        self.label_4.setPixmap(QtGui.QPixmap("asset/friedrice2.png"))
        self.label_4.setObjectName("label_4")
        self.label_5 = QtWidgets.QLabel(self.centralwidget)
        self.label_5.setGeometry(QtCore.QRect(840, 410, 281, 281))
        self.label_5.setText("")
        self.label_5.setPixmap(QtGui.QPixmap("asset/spaghetti.png"))
        self.label_5.setObjectName("label_5")
        self.label_2.raise_()
        self.startButton.raise_()
        self.label_3.raise_()
        self.label.raise_()
        self.label_4.raise_()
        self.label_5.raise_()
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)

        self.startButton.clicked.connect(self.next_window)

        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.startButton.setText(_translate("MainWindow", "START"))

    def next_window(self):
        menu_window = AnotherMainWindow()
        menu_window.show()
        MainWindow.hide()

    
class AnotherMainWindow(QtWidgets.QMainWindow):
    def __init__(self):
        super().__init__()
        self.ui = Ui_MenuWindow()
        self.ui.setupUi(self)


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
